### ISSUE TITLE
Massive Logs

### ISSUE THREAD

**Issue by cpzengel** [electerious/Lychee#359]
Hi, small Website produces massive daily Logs

-rwxrwxrwx 1 root root     166 Dec 24  2013 .htaccess
-rw-r--r-- 1 web3 client0 7.0G May 26 23:54 2015-05-26.log.php
-rw-r--r-- 1 web3 client0 7.5G May 27 23:56 2015-05-27.log.php
-rw-r--r-- 1 web3 client0 7.9G May 28 23:57 2015-05-28.log.php
-rw-r--r-- 1 web3 client0 8.3G May 29 23:52 2015-05-29.log.php
-rw-r--r-- 1 web3 client0 8.7G May 30 23:58 2015-05-30.log.php
-rw-r--r-- 1 web3 client0 9.4G May 31 23:55 2015-05-31.log.php
-rw-r--r-- 1 web3 client0  11G Jun  1 23:57 2015-06-01.log.php
-rw-r--r-- 1 web3 client0  11G Jun  2 23:58 2015-06-02.log.php
-rw-r--r-- 1 web3 client0  10G Jun  3 23:53 2015-06-03.log.php
-rw-r--r-- 1 web3 client0  11G Jun  4 23:48 2015-06-04.log.php
-rw-r--r-- 1 web3 client0  11G Jun  5 23:51 2015-06-05.log.php
-rw-r--r-- 1 web3 client0 5.0G Jun  6 23:59 2015-06-06.log.php
-rw-r--r-- 1 web3 client0  11G Jun  7 23:58 2015-06-07.log.php
-rw-r--r-- 1 web3 client0 9.5G Jun  8 23:59 2015-06-08.log.php
-rw-r--r-- 1 web3 client0 5.9G Jun  9 23:55 2015-06-09.log.php
-rw-r--r-- 1 web3 client0 1.3M Jun 10 23:54 2015-06-10.log.php
-rw-r--r-- 1 web3 client0 385K Jun 11 07:25 2015-06-11.log.php

are those files from lychee?

content like this

#11 /var/www/clients/client0/web3/web/system/libraries/drivers/Config/Array.php(70): require('/var/www/client...')
#12 /var/www/clients/client0/web3/web/system/libraries/drivers/Config.php(111): Config_Array_Driver->load('locale', false)
#13 /var/www/clients/client0/web3/web/system/core/Kohana_Config.php(121): Config_Driver->get('locale.language', false, false)
#14 /var/www/clients/client0/web3/web/system/core/Kohana.php(385): Kohana_Config_Core->get('locale.language', false, false)
#15 /var/www/clients/client0/web3/web/system/core/Kohana.php(150): Kohana_Core::config('locale.language')
#16 /var/www/clients/client0/web3/web/application/Bootstrap.php(49): Kohana_Core::setup()
#17 /var/www/clients/client0/web3/web/index.php(116): require('/var/www/client...')

**Comment by cpzengel** [comment]
sorry, was not lychee, mistake at ispconfig!!! sorry
