### ISSUE TITLE
Gulp error

### ISSUE THREAD

**Issue by bjtaylor1** [electerious/Lychee#622]
I'm getting an error trying to run gulp.
I get:

```shell
root@ip-172-31-43-248:/usr/local/apache2/htdocs/src# gulp
(node:23381) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[08:07:26] Using gulpfile /usr/local/apache2/htdocs/src/gulpfile.js
[08:07:26] Starting 'view--svg'...
[08:07:26] Starting 'view--js'...
[08:07:26] Starting 'main--svg'...
[08:07:26] Starting 'main--js'...
[08:07:26] Starting 'main--styles'...
[08:07:26] 'main--styles' errored after 151 ms
[08:07:26] Error: Missing binding /usr/local/apache2/htdocs/src/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-48/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Linux 64-bit with Node 0.10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (/usr/local/apache2/htdocs/src/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:15:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/apache2/htdocs/src/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:556:32)
[08:07:26] gulp-inject 2 files into view.php.
[08:07:26] gulp-inject 2 files into index.html.
[08:07:26] Finished 'main--svg' after 240 ms
[08:07:26] Finished 'view--svg' after 792 ms
Error in plugin 'gulp-babel'
Message:
    Cannot find module 'lodash/isPlainObject'
[08:07:26] Finished 'view--js' after 785 ms
Error in plugin 'gulp-babel'
Message:
    Cannot find module 'lodash/isPlainObject'
[08:07:26] Finished 'main--js' after 295 ms
```

I tried running
`npm rebuild node-sass`
 which outputs:

```shell
root@ip-172-31-43-248:/usr/local/apache2/htdocs/src# npm rebuild node-sass

> node-sass@3.10.0 install /usr/local/apache2/htdocs/src/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js


> node-sass@3.10.0 postinstall /usr/local/apache2/htdocs/src/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

"/usr/local/apache2/htdocs/src/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-11/binding.node" exists.
 testing binary.
Binary is fine; exiting.

> node-sass@3.8.0 install /usr/local/apache2/htdocs/src/node_modules/node-sass
> node scripts/install.js


> node-sass@3.8.0 postinstall /usr/local/apache2/htdocs/src/node_modules/node-sass
> node scripts/build.js

"/usr/local/apache2/htdocs/src/node_modules/node-sass/vendor/linux-x64-11/binding.node" exists.
 testing binary.
Binary is fine; exiting.
node-sass@3.10.0 /usr/local/apache2/htdocs/src/node_modules/gulp-sass/node_modules/node-sass
node-sass@3.8.0 /usr/local/apache2/htdocs/src/node_modules/node-sass
root@ip-172-31-43-248:/usr/local/apache2/htdocs/src#
```

however gulp returns the same error as above.

Any help much appreciated!

(sorry, I've got 'htdocs' as the git source root by the way - not sure if that's advisable but simplest way of getting it at the root of my web server)

**Comment by electerious** [comment]
I don't know the reason for the error, but it definitely has something to do with node-sass and your environment. Shouldn't be a problem of Lychee. Let me know when I'm wrong.

**Comment by bjtaylor1** [comment]
It was more a question/plea for help than a problem of lychee. No matter.

**Comment by electerious** [comment]
Asking that question here isn't a problem! :) I would really like to help, but I'm not sure what's causing the issue. You will have more luck in npm/node-sass related forums.
